-- MySQL Script generated by MySQL Workbench
-- sex 02 jun 2017 20:32:30 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bookapi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookapi` ;

-- -----------------------------------------------------
-- Schema bookapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookapi` DEFAULT CHARACTER SET utf8 ;
USE `bookapi` ;

-- -----------------------------------------------------
-- Table `bookapi`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookapi`.`author` ;

CREATE TABLE IF NOT EXISTS `bookapi`.`author` (
  `id_author` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_author`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookapi`.`publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookapi`.`publisher` ;

CREATE TABLE IF NOT EXISTS `bookapi`.`publisher` (
  `publisher_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`publisher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookapi`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookapi`.`book` ;

CREATE TABLE IF NOT EXISTS `bookapi`.`book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(20) NULL,
  `name` VARCHAR(80) NOT NULL,
  `fk_publisher_id` INT NOT NULL,
  PRIMARY KEY (`book_id`),
  INDEX `fk_publisher_id_idx` (`fk_publisher_id` ASC),
  CONSTRAINT `fk_publisher_id`
    FOREIGN KEY (`fk_publisher_id`)
    REFERENCES `bookapi`.`publisher` (`publisher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookapi`.`author_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookapi`.`author_book` ;

CREATE TABLE IF NOT EXISTS `bookapi`.`author_book` (
  `author_book_id` INT NOT NULL AUTO_INCREMENT,
  `fk_author_id` INT NOT NULL,
  `fk_book_id` INT NOT NULL,
  INDEX `fk_author_has_book_book1_idx` (`fk_book_id` ASC),
  PRIMARY KEY (`author_book_id`),
  CONSTRAINT `fk_author_book_author_id`
    FOREIGN KEY (`fk_author_id`)
    REFERENCES `bookapi`.`author` (`id_author`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_author_book_book_id`
    FOREIGN KEY (`fk_book_id`)
    REFERENCES `bookapi`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
